### ISSUE TITLE
increase max number of projected textures

### ISSUE THREAD

**Issue by maksw2** [Sectonidse/SourceDEFUN#5]
from 1 to 4 please

**Comment by Sectonidse** [comment]
From 1:
https://github.com/Sectonidse/SourceDEFUN/blob/456e4ff1c179725fc327aeb0c97b37a358baa075/game/client/clientshadowmgr.cpp#L1407

To 32 because why not more?:
https://github.com/Sectonidse/SourceDEFUN/blob/079347a65f3a1687f92ca0b906a9a390639fc797/game/client/clientshadowmgr.cpp#L1407

**Comment by maksw2** [comment]
actually, 32 might be too much. as stated in the wiki a shadow map is created for every one, even when it's not used. that means it would be a waste of cpu/gpu power. the safe limit is 10.

**Comment by Sectonidse** [comment]
Decreased to 8 in https://github.com/Sectonidse/SourceDEFUN/commit/81e7d0c263d0db23821f943366b9071d8eb9b66d
Honestly, i thought why not add more because i was thinking that it will create a shadow map only to those that already exist or is visible/enabled.

I don't think it's possible to make the creation of shadow maps only to those that exist though, might be the core feature of Source Base, the code of which we will never get...

**Comment by maksw2** [comment]
the best we can do is to add engine code from leaks, but i don't recommend that.
